export let qu = {'r01_a1': 'R01_A1. Školy by měly učit děti uznávat autoritu.',
'r01_a2': 'R01_A2. Silný vůdce je důležitý pro Českou republiku, i když nebude vždy jednat v souladu se zavedenými pravidly.',
'r01_k1': 'R01_K1. Nejlepší je dělat věci tradičními způsoby, postaru.',
'r01_k2': 'R01_K2. Příslušníci menšin by se měli přizpůsobit českým zvykům a tradicím.',
'r01_p1': 'R01_P1. Lidé, a nikoliv politici by měli dělat nejdůležitější rozhodnutí ve společnosti.',
'r01_p2': 'R01_P2. Obyčejní lidé se v\xa0pohledu na politiku a společnost lépe shodnou mezi sebou, než s\xa0politiky a elitami.',
'r01_lp1': 'R01_LP1. Lidé s vysokým příjmem a bohatí by na daních měli platit vyšší procento ze svého příjmu či majetku.',
'r01_lp2': 'R01_LP2. Volný trh by takřka nikdy neměl být omezován státními regulacemi.',
'r01_n1': 'R01_N1. Ekonomické a společenské nerovnosti v\xa0Česku jsou příliš velké.',
'r01_n2': 'R01_N2. Úspěch v\xa0Česku závisí spíše na tom, kde a do jaké rodiny se narodíte, než na vlastní snaze.',
'r01_np1': 'R01_NP1. Jsem hrdý/-á na to, že jsem příslušníkem svého národa.',
'r01_np2': 'R01_NP2. Kultura mého národa je lepší než většina ostatních.',
'r01_v1': 'R01_V1. Věřím v\xa0Boha, tak jak ho chápe křesťanství či jiné náboženství.',
'r01_v2': 'R01_V2. Ve svém životě se snažím dodržovat hodnoty Desatera.',
'r01_m1': 'R01_M1. Věci, které člověk vlastní, říkají hodně o tom, jak dobrý život vede.',
'r01_m2': 'R01_M2. Byl/a bych v životě spokojenější a šťastnější, pokud bych si mohl/a dovolit pořídit věci, které dnes nevlastním.',
'cont1': 'KONTOLA1.  V tomto řádku pro kontrolu pozornosti vyberte možnost Spíše nesouhlasím',
'r01_zj1': 'R01_ZJ1. Téměř každý den sleduji vývoj na naší politické scéně.',
'r01_zj2': 'R01_ZJ2. Zajímám se o mezinárodní události.',
'r01_g1': 'R01_G1. Lidé jako jsem já na globalizaci a moderních trendech ve společnosti výrazně vydělávají.',
'r01_g2': 'R01_G2. Velké nadnárodní firmy vydělávají na úkor České republiky.',
'r01_g3': 'R01_G3. Vývoj dnešní společnosti nelze předvídat, což mne velmi zneklidňuje.',
'r01_z1': 'R01_Z1. Členství v\xa0EU je pro nás prospěšné.',
'r01_z2': 'R01_Z2. Členství v\xa0NATO je pro nás prospěšné.',
'r01_z3': 'R01_Z3. Česko patří na Západ.',
'r01_h1': 'R01_H1. Společnost se po roce 1989 ubírá obecně správným směrem.',
'r01_h2': 'R01_H2. Politici a lídři v\xa0posledních 30 letech většinu věcí zkazili.',
'r01_i1': 'R01_I1. Imigranti způsobují nárůst trestné činnosti.',
'r01_i2': 'R01_I2. Imigranti ohrožují náš způsob života.',
'r01_i3': 'R01_I3. Imigranti ohrožují českou ekonomiku a sociální jistoty.',
'r01_vz1': 'R01_VZ1. Více dětí než dnes by mělo chodit studovat na učiliště.',
'r01_vz2': 'R01_VZ2. V základním školství bychom měli oddělovat talentované studenty od méně nadaných.',
'r01_e1': 'R01_E1. Člověkem způsobené klimatické změny zásadně ohrožují naši budoucnost.',
'r01_e2': 'R01_E2. Byl/a bych ochoten/ochotna obětovat 5 % svých příjmů, pokud bych věděl/a, že to pomůže ochraně životního prostředí.',
'r01_ind1': 'R01_IND1. Dnes se člověk musí ohlížet především na to, co je výhodné pro něj osobně.',
'r01_pol1': 'R01_POL1. Společnost je rozdělená na dva nesmiřitelné tábory.',
'r01_pos1': 'R01_POS1. I když se to někdy nezdá, naše společnost funguje ve vzájemném souladu.'}