export const qu = {
    'predel_1': 'Obavy z migrace',
    'r01_i1': 'Imigranti způsobují nárůst trestné činnosti.',
    'r01_i2': 'Imigranti ohrožují náš způsob života.',
    'r01_i3': 'Imigranti ohrožují českou ekonomiku a sociální jistoty.',
    'predel_2': 'Vnímání nerovností – rovnostářství, zásluhovost, přerozdělování',
    'r01_lp1': 'Lidé s vysokým příjmem a bohatí by na daních měli platit vyšší procento ze svého příjmu či majetku.',
    'r01_n1': 'Ekonomické a společenské nerovnosti v Česku jsou příliš velké.',
    'r01_n2': 'Úspěch v Česku závisí spíše na tom, kde a do jaké rodiny se narodíte, než na vlastní snaze.',
    'predel_3': 'Prozápadní směřování',
    'r01_z1': 'Členství v EU je pro nás prospěšné.',
    'r01_z2': 'Členství v NATO je pro nás prospěšné.',
    'r01_z3': 'Česko patří na Západ.',
    'predel_4': 'Vývoj po roce 1989 a využité šance',
    'r01_h1': 'Společnost se po roce 1989 ubírá obecně správným směrem.',
    'r01_h2': 'Politici a lídři v posledních 30 letech většinu věcí zkazili.',
    'predel_5': 'Více rozhodování lidem, méně voleným politikům',
    'r01_p1': 'Lidé, a nikoliv politici by měli dělat nejdůležitější rozhodnutí ve společnosti.',
    'r01_p2': 'Obyčejní lidé se v pohledu na politiku a společnost lépe shodnou mezi sebou, než s politiky a elitami.',
    'predel_6': 'Korporace vydělávají na úkor ČR',
    'r01_g2': 'Velké nadnárodní firmy vydělávají na úkor České republiky.',
    'predel_7': 'Společnost je rozdělená na dva tábory',
    'r01_pol1': 'Společnost je rozdělená na dva nesmiřitelné tábory.',
    'predel_8': 'Materialismus – nutnost prosadit vlastní zájmy, důležitost majetku',
    'r01_m1': 'Věci, které člověk vlastní, říkají hodně o tom, jak dobrý život vede.',
    'r01_m2': 'Byl/a bych v životě spokojenější a šťastnější, pokud bych si mohl/a dovolit pořídit věci, které dnes nevlastním.',
    'r01_ind1': 'Dnes se člověk musí ohlížet především na to, co je výhodné pro něj osobně.',
    'predel_9': 'Společnost stojící na autoritě – silný vůdce, přizpůsobení se',
    'r01_k2': 'Příslušníci menšin by se měli přizpůsobit českým zvykům a tradicím.',
    'r01_a2': 'Silný vůdce je důležitý pro Českou republiku, i když nebude vždy jednat v souladu se zavedenými pravidly.',
    'r01_a1': 'Školy by měly učit děti uznávat autoritu.',
    'predel_10': 'Nejistota z budoucího vývoje',
    'r01_g3': 'Vývoj dnešní společnosti nelze předvídat, což mne velmi zneklidňuje.',
    'predel_11': 'Nadřazenost vlastní kultury',
    'r01_np2': 'Kultura mého národa je lepší než většina ostatních.',
    'predel_12': 'Více žáků na učiliště',
    'r01_vz1': 'Více dětí než dnes by mělo chodit studovat na učiliště.',
    'predel_13': 'Zájem o politiku a dění okolo sebe',
    'r01_zj1': 'Téměř každý den sleduji vývoj na naší politické scéně.',
    'r01_zj2': 'Zajímám se o mezinárodní události.',
    'predel_14': 'Víra v Boha',
    'r01_v1': 'Věřím v Boha, tak jak ho chápe křesťanství či jiné náboženství.',
    'predel_15': 'Životní prostředí – klima a ochota se omezit',
    'r01_e1': 'Člověkem způsobené klimatické změny zásadně ohrožují naši budoucnost.',
    'r01_e2': 'Byl/a bych ochoten/ochotna obětovat 5 % svých příjmů, pokud bych věděl/a, že to pomůže ochraně životního prostředí.',
    'predel_16': 'V české společnosti je soulad',
    'r01_pos1': 'I když se to někdy nezdá, naše společnost funguje ve vzájemném souladu.',
    'predel_17': 'Rozdělování studentů podle nadání',
    'r01_vz2': 'V základním školství bychom měli oddělovat talentované studenty od méně nadaných.',
    'predel_18': 'Patriotismus - hrdost na vlastní zemi',
    'r01_np1': 'Jsem hrdý/-á na to, že jsem příslušníkem svého národa.',
}